language: ruby
dist: trusty
rvm:
  - 2.4.4
  - 2.6.3
  - 2.6.5
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite
before_install:
  - gem install -N bundler
bundler_args: --without capistrano doc production --jobs 2
before_script:
  - cp config/database.yml.travis config/database.yml
  - sed -i 's/config.eager_load = .*/config.eager_load = true/' config/environments/test.rb
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database frab_test'; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'create database frab_test' -U postgres; fi"
script:
  - RAILS_ENV=test bundle exec rails db:schema:load --trace
  - bundle exec rails db:test:prepare
  - bundle exec rails test
