language: ruby
rvm:
  - 2.4.1
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite
bundler_args: --without capistrano doc production --jobs 2
before_script:
  - cp config/database.yml.travis config/database.yml
  - mysql -e 'create database frab_test'
  - psql -c 'create database frab_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rails db:schema:load --trace
  - bundle exec rails db:test:prepare
  - bundle exec rails test
